# Site settings
title: Mark Buckner's home page
short_logo: M. Buckner
description: >
  A Jekyll website hosted on GitHub for use as my personal site to show code projects and blog posts.
baseurl: "/personal-site" # the subpath of your site, e.g. /blog/
url: "https://markbuckner.github.io" # the base hostname & protocol for your site

author:
  fullname: Mark Bucknre
  github: /markbuckner
  linkedin: /mark-buckner-io
  email: marbuckner@protonmail.com

disqus_name: 
g_track_id: 

markdown: kramdown

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true
      listed: true
      author: Mark Buckner
      author_link: <a href="https://github.com/markbuckner/">Mark Buckner<a>
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false
